spring:
  application:
    name: eda-consumer-create-orders
  rabbitmq:
    host: eda-rabbitmq
    port: 5672
    username: admin
    password: admin
  data:
    mongodb:
      host: eda-mongodb
      port: 27017
      username: admin
      password: admin
      authentication-database: admin
      database: sua_base_de_dados

rabbitmq:
  consumer:
    kt-order:
      queue: create-order-dlq
      exchange: exg.direct.order
      routing-key: rk.order.dlq